# Practice

In [1]:
import numpy as np


In [2]:
arr = np.array([2,3,4])

In [3]:
arr[0]

np.int64(2)

In [4]:
arr.shape

(3,)

In [5]:
arr.dtype

dtype('int64')

# Array Creation from Numpy

In [2]:
import numpy as np
listarr = np.array([[1,2,3],[4,5,6],[7,8,9]])
listarr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
listarr[2][2]=10

In [9]:
listarr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8, 10]])

In [11]:
zeros = np.zeros((2,2))
zeros

array([[0., 0.],
       [0., 0.]])

In [12]:
rng = np.arange(10)

In [13]:
rng

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
lspace = np.linspace(1,5,12)
lspace

array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

In [15]:
arr = np.arange(99)

In [16]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [17]:
arr.reshape(3,33)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [18]:
arr.shape

(99,)

In [19]:
x=[[1,2,3],[4,5,6],[7,1,0]]
ar = np.array(x)

In [20]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [21]:
ar.sum(axis=0)

array([12,  8,  9])

In [23]:
ar.sum(axis=1)

array([ 6, 15,  8])

In [24]:
ar.T

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [25]:
one = np.array([1,3,4,634,2])

In [26]:
one.argmax()

np.int64(3)

In [27]:
ar.argmax(axis=0)

array([2, 1, 1])

In [28]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [31]:
ar2 =np.array([[1, 2, 1],
       [4, 0, 6],
       [8, 1, 0]])

In [32]:
ar+ar2

array([[ 2,  4,  4],
       [ 8,  5, 12],
       [15,  2,  0]])

In [33]:
np.sqrt(ar)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 1.        , 0.        ]])

In [34]:
np.where(ar>5)

(array([1, 2]), array([2, 0]))

Above line finds all the places where element is greater than 5