# Tutorial 1 .
Basic Understanding about numpy functions .

In [1]:
import numpy as np
import pandas as pd

## MultiDimensional Arrays

In [3]:
a1 = np.array([1,2,3])
a2 = np.array([4,5,6])
a3 = np.array([7,8,9])
arr_2d = np.vstack((a1,a2,a3))
print("---1D---")
print(a1)
print("---2D---")
print(arr_2d)
print("---3D---")
arr_3d = np.array([arr_2d,arr_2d,arr_2d])
arr_3d

---1D---
[1 2 3]
---2D---
[[1 2 3]
 [4 5 6]
 [7 8 9]]
---3D---


array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

## Sum of Arrays

In [4]:
print("Row Sum ", np.sum(arr_2d,axis=0))
print("Column Sum",np.sum(arr_2d,axis=1))

Row Sum  [12 15 18]
Column Sum [ 6 15 24]


In [5]:
arr= np.array([range(5),range(5,10)])
arr

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [7]:
arr.shape

(2, 5)

In [8]:
ar1 = np.arange(2,10,3)
ar1

array([2, 5, 8])