In [33]:
#DecisionTreeClassification
import numpy as np 
import pandas as pd 

In [34]:
#Reading the dataset
df = pd.read_csv("./Datasets/student-mat.csv",sep=";")
df.head()

school sex  age address famsize Pstatus  Medu  Fedu     Mjob      Fjob  ...  \
0     GP   F   18       U     GT3       A     4     4  at_home   teacher  ...   
1     GP   F   17       U     GT3       T     1     1  at_home     other  ...   
2     GP   F   15       U     LE3       T     1     1  at_home     other  ...   
3     GP   F   15       U     GT3       T     4     2   health  services  ...   
4     GP   F   16       U     GT3       T     3     3    other     other  ...   

  famrel freetime  goout  Dalc  Walc health absences  G1  G2  G3  
0      4        3      4     1     1      3        6   5   6   6  
1      5        3      3     1     1      3        4   5   5   6  
2      4        3      2     2     3      3       10   7   8  10  
3      3        2      2     1     1      5        2  15  14  15  
4      4        3      2     1     2      5        4   6  10  10  

[5 rows x 33 columns]

In [35]:
df.isna().sum()

school        0
sex           0
age           0
address       0
famsize       0
Pstatus       0
Medu          0
Fedu          0
Mjob          0
Fjob          0
reason        0
guardian      0
traveltime    0
studytime     0
failures      0
schoolsup     0
famsup        0
paid          0
activities    0
nursery       0
higher        0
internet      0
romantic      0
famrel        0
freetime      0
goout         0
Dalc          0
Walc          0
health        0
absences      0
G1            0
G2            0
G3            0
dtype: int64

In [36]:
X = df.iloc[:, np.r_[0:21, 23:-1]]
X

school sex  age address famsize Pstatus  Medu  Fedu      Mjob      Fjob  \
0       GP   F   18       U     GT3       A     4     4   at_home   teacher   
1       GP   F   17       U     GT3       T     1     1   at_home     other   
2       GP   F   15       U     LE3       T     1     1   at_home     other   
3       GP   F   15       U     GT3       T     4     2    health  services   
4       GP   F   16       U     GT3       T     3     3     other     other   
..     ...  ..  ...     ...     ...     ...   ...   ...       ...       ...   
390     MS   M   20       U     LE3       A     2     2  services  services   
391     MS   M   17       U     LE3       T     3     1  services  services   
392     MS   M   21       R     GT3       T     1     1     other     other   
393     MS   M   18       R     LE3       T     3     2  services     other   
394     MS   M   19       U     LE3       T     1     1     other   at_home   

     ... guardian traveltime  studytime  failures  schoolsup famsup paid  \
0    ...   mother          2          2         0        yes     no   no   
1    ...   father          1          2         0         no    yes   no   
2    ...   mother          1          2         3        yes     no  yes   
3    ...   mother          1          3         0         no    yes  yes   
4    ...   father          1          2         0         no    yes  yes   
..   ...      ...        ...        ...       ...        ...    ...  ...   
390  ...    other          1          2         2         no    yes  yes   
391  ...   mother          2          1         0         no     no   no   
392  ...    other          1          1         3         no     no   no   
393  ...   mother          3          1         0         no     no   no   
394  ...   father          1          1         0         no     no   no   

    activities nursery higher  
0           no     yes    yes  
1           no      no    yes  
2           no     yes    yes  
3          yes     yes    yes  
4           no     yes    yes  
..         ...     ...    ...  
390         no     yes    yes  
391         no      no    yes  
392         no      no    yes  
393         no      no    yes  
394         no     yes    yes  

[395 rows x 21 columns]

In [37]:
Y = df.iloc[:,22]
Y

0       no
1       no
2       no
3      yes
4       no
      ... 
390     no
391     no
392     no
393     no
394     no
Name: romantic, Length: 395, dtype: object

In [38]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder , StandardScaler

In [39]:
X_train ,X_test , y_train,  y_test = train_test_split(X,Y,random_state=42)

In [40]:
X_train.shape

(296, 21)

In [41]:

y_train.shape

(296,)

In [42]:
X_train_cols = X_train.select_dtypes(include='object')
X_train_num = X_train.select_dtypes(include='number')

In [43]:
one = OneHotEncoder(drop="first",sparse_output=False)
scaler = StandardScaler()

In [44]:
X_train_cols_enc = one.fit_transform(X_train_cols)

In [45]:
X_train_cols_enc.shape

(296, 24)

In [46]:
X_train_num_enc = scaler.fit_transform(X_train_num)
X_train_num_enc

array([[-0.57868312,  1.16265527,  1.35873244, -0.61341056,  1.13079867,
        -0.45919897],
       [-1.36441799,  1.16265527,  1.35873244, -0.61341056,  2.32621441,
        -0.45919897],
       [ 0.20705176,  1.16265527,  1.35873244, -0.61341056, -0.06461707,
        -0.45919897],
       ...,
       [ 1.77852151,  0.23503813,  0.4277491 , -0.61341056, -0.06461707,
         2.25925895],
       [ 0.20705176,  1.16265527,  0.4277491 , -0.61341056,  1.13079867,
        -0.45919897],
       [-1.36441799,  1.16265527,  1.35873244, -0.61341056, -1.26003281,
        -0.45919897]], shape=(296, 6))

In [47]:
X_test_cols = X_test.select_dtypes(include='object')
X_test_num = X_test.select_dtypes(include='number')

In [48]:
X_test_cols_enc = one.transform(X_test_cols)

In [49]:
X_test_num_enc = scaler.transform(X_test_num)

In [50]:
df_cols_enc = pd.DataFrame(X_train_cols_enc)
df_num_enc = pd.DataFrame(X_train_num_enc)
X_train_encoded = pd.concat([df_cols_enc, df_num_enc], axis=1)

In [51]:
df_test_cols_enc = pd.DataFrame(X_test_cols_enc)
df_test_num_enc = pd.DataFrame(X_test_num_enc)

X_test_encoded = pd.concat([df_test_cols_enc, df_test_num_enc], axis=1)

In [52]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [53]:
Y

0       no
1       no
2       no
3      yes
4       no
      ... 
390     no
391     no
392     no
393     no
394     no
Name: romantic, Length: 395, dtype: object

In [54]:
y_train.head()

16      no
66     yes
211    yes
7       no
19      no
Name: romantic, dtype: object

In [55]:
from sklearn.tree import DecisionTreeClassifier

In [56]:
model = DecisionTreeClassifier(criterion='gini',max_depth=3,random_state=42)


In [57]:
y_train_enc = le.fit_transform(y_train)

In [58]:
y_test_enc = le.fit_transform(y_test)

In [59]:
y_train_enc.shape

(296,)

In [60]:
model.fit(X_train_encoded,y_train_enc)

DecisionTreeClassifier(max_depth=3, random_state=42)

In [61]:
y_pred = model.predict(X_test_encoded)

In [62]:
y_pred

array([1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0])

In [63]:
from sklearn.metrics import classification_report , confusion_matrix

In [64]:
cm = confusion_matrix(y_test_enc,y_pred)

In [65]:
cm

array([[50, 17],
       [22, 10]])

In [66]:
print("Classification Report : ")
print(classification_report(y_test_enc,y_pred))

Classification Report : 
              precision    recall  f1-score   support

           0       0.69      0.75      0.72        67
           1       0.37      0.31      0.34        32

    accuracy                           0.61        99
   macro avg       0.53      0.53      0.53        99
weighted avg       0.59      0.61      0.60        99

